name: build_vanadium_v2
run-name: ${{ github.actor }}
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone_Vanadium
        id: clone_vanadium
        run: git clone https://github.com/GrapheneOS/Vanadium.git

