name: build_vanadium_v2
run-name: ${{ github.actor }}
on:
  push:
    branches: [ main ]
jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: apt install git -y
      - run: git clone https://github.com/GrapheneOS/Vanadium.git

