name: build_vanadium_v2
run-name: ${{ github.actor }}
on:
  push:
    branches: [ main ]
jobs:
    runs-on: ubuntu-latest
    steps:
      - name: install_git
        id: install_git
        run: | apt install git -y

